&PARAM_ADVECT3D
  NeX = 8,
  NeY = 8,
  NeZ = 8,
  PolyOrder = 31,
  DGOptrKernel_OptType = "OPT1"
  DqdtKernel_Type = "CUDAFORTRAN_FUSED_TC"
  dt    = 1.0D-6,
  nstep = 5,
  output_interval = 5,
  UseCudaGraph = .false.
  WarmupStep = 1
/
