&PARAM_ADVECT3D
  NeX = 32,
  NeY = 32,
  NeZ = 32,
  PolyOrder = 7,
  DGOptrKernel_OptType = "OPT1" ! GENERAL or OPT1
  !--------------------
  dt    = 1.0D-5,
  nstep = 1000,
  output_interval = 100,
/
