&PARAM_ADVECT3D
  NeX = 4,
  NeY = 4,
  NeZ = 4,
  PolyOrder = 7,
  DGOptrKernel_OptType = "OPT1" ! GENERAL or OPT1
  DqdtKernel_Type = "OPENACC_SPLIT" ! OPENACC_ASIS or OPENACC_SPLIT
  !--------------------
  dt    = 1.0D-3,
  nstep = 1000,
  output_interval = 100,
/
