&PARAM_ADVECT3D
  NeX = 32,
  NeY = 32,
  NeZ = 32,
  PolyOrder = 7,
  DGOptrKernel_OptType = "OPT1"
  DqdtKernel_Type = "CUDAFORTRAN_GEMM_FUSED"
  CublasEmulation = .false.
  UseCudaGraph = .false.
  dt    = 1.0D-5,
  nstep = 20,
  output_interval = 100,
/
