&PARAM_ADVECT3D
  NeX = 16,
  NeY = 16,
  NeZ = 16,
  PolyOrder = 15,
  DGOptrKernel_OptType = "OPT1"
  DqdtKernel_Type = "CUDAFORTRAN_FUSED_DFMA"
  CublasEmulation = .false.
  UseCudaGraph = .false.
  dt    = 1.0D-5,
  nstep = 20,
  output_interval = 100,
/
