&PARAM_ADVECT3D
  NeX = 4,
  NeY = 4,
  NeZ = 4,
  PolyOrder = 63,
  DGOptrKernel_OptType = "OPT1"
  DqdtKernel_Type = "CUDAFORTRAN_FUSED_TC"
  CublasEmulation = .false.
  UseCudaGraph = .false.
  dt    = 1.0D-6,
  nstep = 20,
  output_interval = 100,
/
