&PARAM_ADVECT3D
  NeX = 2,
  NeY = 2,
  NeZ = 2,
  PolyOrder = 7,
  DGOptrKernel_OptType = "OPT1"
  DqdtKernel_Type = "CUDAFORTRAN_GEMM_FUSED"
  CublasEmulation = .false.
  dt    = 1.0D-5,
  nstep = 1,
  output_interval = 1,
/
